# SPDX-License-Identifier: AGPL-3.0-only
"""Build the shuffled, balanced prompt pool for on-policy drafter data.

Prompts only; responses are generated by our serving target. Every prefix of
the output is a balanced mix of sources, languages, thinking modes and sampling
settings, so generation can stop at any point. Needs pyarrow (drafter venv).
"""
import argparse
import collections
import gzip
import hashlib
import json
from pathlib import Path
import random
import re

import pyarrow.parquet as pq

RAW = Path(__file__).resolve().parents[3] / 'artifacts/drafter-data/raw'
MAX_CHARS, LONG_CHARS = 8000, 60000


def rows(path, columns=None):
    return pq.read_table(path, columns=columns).to_pylist()


def ok(text, limit=MAX_CHARS):
    return isinstance(text, str) and 8 <= len(text.strip()) <= limit


def perfectblend(rng, n):
    out = []
    for f in sorted((RAW / 'mlabonne__open-perfectblend/data').glob('*.parquet')):
        for r in rows(f):
            conv = r['conversations']
            if conv and conv[0]['from'] == 'human' and ok(conv[0]['value']):
                out.append(dict(source='perfectblend/' + r['source'], category='mixed',
                                messages=[dict(role='user', content=conv[0]['value'])]))
    return rng.sample(out, n)


def wildchat(rng, n_single, n_multi, n_long):
    by_lang, multi, long = collections.defaultdict(list), [], []
    for f in sorted((RAW / 'allenai__WildChat-1M/data').glob('*.parquet')):
        for r in rows(f, ['conversation', 'language', 'toxic', 'redacted']):
            if r['toxic'] or r['redacted']:
                continue
            conv = [dict(role=m['role'], content=m['content']) for m in r['conversation']]
            if not conv or conv[0]['role'] != 'user':
                continue
            lang = r['language'] or 'unknown'
            if ok(conv[0]['content']):
                by_lang[lang].append(dict(source='wildchat', category='chat', language=lang, messages=conv[:1]))
            elif ok(conv[0]['content'], LONG_CHARS):
                long.append(dict(source='wildchat', category='long_input', language=lang, messages=conv[:1]))
            # Multi-turn: keep k earlier exchanges, regenerate the next assistant turn.
            users = [i for i, m in enumerate(conv) if m['role'] == 'user']
            if len(users) >= 2:
                cut = users[rng.randrange(1, len(users))]
                ctx = conv[:cut + 1]
                if all(ok(m['content'], 6000) for m in ctx) and sum(len(m['content']) for m in ctx) < 16000:
                    multi.append(dict(source='wildchat', category='multi_turn', language=lang, messages=ctx))
    # Language-stratified: English capped at 35%, the rest proportional with a floor.
    pick = []
    other = {k: v for k, v in by_lang.items() if k != 'English'}
    pick += rng.sample(by_lang['English'], min(len(by_lang['English']), int(n_single * .35)))
    rest = n_single - len(pick)
    total = sum(len(v) for v in other.values())
    for lang, items in sorted(other.items(), key=lambda kv: -len(kv[1])):
        take = min(len(items), max(15, round(rest * len(items) / total)))
        pick += rng.sample(items, take)
    return rng.sample(pick, min(n_single, len(pick))) + rng.sample(multi, n_multi) + rng.sample(long, min(n_long, len(long)))


def aya(rng, n):
    by_lang = collections.defaultdict(list)
    for r in rows(RAW / 'CohereLabs__aya_dataset/data/train-00000-of-00001.parquet', ['inputs', 'language']):
        if ok(r['inputs']):
            by_lang[r['language']].append(dict(source='aya', category='multilingual', language=r['language'],
                                                messages=[dict(role='user', content=r['inputs'])]))
    per = n // len(by_lang) + 1
    out = [x for items in by_lang.values() for x in rng.sample(items, min(per, len(items)))]
    return rng.sample(out, min(n, len(out)))


def oasst(rng, n):
    out = []
    with gzip.open(RAW / 'OpenAssistant__oasst2/2023-11-05_oasst2_ready.trees.jsonl.gz', 'rt') as f:
        for line in f:
            p = json.loads(line)['prompt']
            if ok(p['text']):
                out.append(dict(source='oasst2', category='multilingual', language=p.get('lang'),
                                messages=[dict(role='user', content=p['text'])]))
    return rng.sample(out, n)


def code(rng, n_each):
    mc = [json.loads(l) for l in open(RAW / 'ise-uiuc__Magicoder-OSS-Instruct-75K/data-oss_instruct-decontaminated.jsonl')]
    cf = [json.loads(l) for l in open(RAW / 'm-a-p__CodeFeedback-Filtered-Instruction/CodeFeedback-Filtered-Instruction.jsonl')]
    a = [dict(source='magicoder', category='code', language=r.get('lang'), messages=[dict(role='user', content=r['problem'])])
         for r in mc if ok(r['problem'])]
    b = [dict(source='codefeedback', category='code', language=r.get('lang'), messages=[dict(role='user', content=r['query'])])
         for r in cf if ok(r['query'])]
    return rng.sample(a, n_each) + rng.sample(b, n_each)


def glaive(rng, n):
    out = []
    for r in json.load(open(RAW / 'glaiveai__glaive-function-calling-v2/glaive-function-calling-v2.json')):
        system, chat = r['system'], r['chat']
        m = re.search(r'USER:(.*?)(?:ASSISTANT:|$)', chat, re.S)
        if not m or not ok(m.group(1).strip()):
            continue
        tools = []
        for block in re.findall(r'\{.*?\n\}', system.split('-', 1)[-1], re.S):
            try:
                fn = json.loads(block)
                tools.append(dict(type='function', function=fn))
            except json.JSONDecodeError:
                pass
        if tools:
            out.append(dict(source='glaive', category='tools', messages=[dict(role='user', content=m.group(1).strip())],
                            tools=tools))
    return rng.sample(out, n)


def math(rng, n):
    out = [dict(source='openmath', category='math', messages=[dict(role='user', content=r['problem'])])
           for r in rows(RAW / 'nvidia__OpenMathReasoning/data/additional_problems-00000-of-00001.parquet', ['problem'])
           if ok(r['problem'])]
    return rng.sample(out, n)


def magpie(rng, n):
    out = [dict(source='magpie', category='mixed/' + (r['primary_tag'] or ''), messages=[dict(role='user', content=r['instruction'])])
           for r in rows(RAW / 'argilla__magpie-ultra-v1.0/data/train-00000-of-00056.parquet', ['instruction', 'primary_tag'])
           if ok(r['instruction'])]
    return rng.sample(out, min(n, len(out)))


def settings(rng, item):
    item['thinking'] = rng.random() < .6
    if item['thinking']:
        item['reasoning_effort'] = rng.choices([None, 'low', 'high'], [.6, .2, .2])[0]
        item['max_tokens'] = 8192
    else:
        item['max_tokens'] = 4096
    u = rng.random()
    item['temperature'], item['top_p'] = (0.0, 1.0) if u < .15 else (1.0, 1.0) if u < .20 else (1.0, 0.95)
    return item


def main():
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument('--output', type=Path, required=True)
    p.add_argument('--seed', type=int, default=41)
    a = p.parse_args()
    rng = random.Random(a.seed)
    pool = (perfectblend(rng, 16000) + wildchat(rng, 12000, 2000, 2000) + aya(rng, 6000) + oasst(rng, 2500)
            + code(rng, 3500) + glaive(rng, 3000) + math(rng, 3000) + magpie(rng, 4000))
    seen, unique = set(), []
    for item in pool:
        key = hashlib.sha256(json.dumps(item['messages'], sort_keys=True).encode()).hexdigest()
        if key not in seen:
            seen.add(key)
            unique.append(settings(rng, dict(item, id=key[:16])))
    rng.shuffle(unique)
    with a.output.open('x') as out:
        for item in unique:
            out.write(json.dumps(item, ensure_ascii=False) + '\n')
    c = collections.Counter(i['source'].split('/')[0] for i in unique)
    langs = collections.Counter(i.get('language') for i in unique)
    print(json.dumps(dict(prompts=len(unique), sources=c, thinking=sum(i['thinking'] for i in unique),
                          distinct_languages=len(langs), top_languages=langs.most_common(12)), default=str))


if __name__ == '__main__':
    main()
